v1/fleet-local/control/zk-exhibitor@.service, v1/fleet/control-jenkins.service, v1/fleet/control-proxy.service, v1/fleet/logrotate.service, v1/opt/datadog/datadog-control.service, v1/opt/datadog/datadog-mesos-master.service, v1/opt/datadog/datadog-mesos-slave.service, v1/opt/datadog/datadog-proxy.service, v1/opt/datadog/datadog.service, v1/opt/ecr/aws-ecr-login.service, v1/opt/splunk/splunk-journald.service, v1/opt/sumologic/sumologic-control.service, v1/opt/sumologic/sumologic-journald.service, v1/opt/sumologic/sumologic.service, v1/setup/leader/001-defaults.sh
* Added `After bootstrap.service` to all units that use etcd values
* Using `$($IMAGE)` obtained from etcd in all units
=> Using etcd images and wait for bootstraps

v1/fleet/control-jenkins.service, v1/util/jenkins-update-config.sh
* Migrating PR from here: https://github.com/adobe-platform/mesos-systemd/pull/175/
=> Adding Okta Jenkins from mesos-systemd

v1/fleet-local/control/flight-director@.service, v1/setup/leader/001-defaults.sh
* Added an IAM role label for use with Flight Director
Did you introduce any command that executes `docker run`? No
If you did, have you ensured that all your `docker run` using the default logger have either `max-size` and/or `max-file` set? N/A
Are there any dependencies on github.com/adobe-platform/infrastructure? No
If so:
=> Iam role label

v1/setup/bastion/001-defaults.sh, v1/setup/leader/001-defaults.sh
=> removed unused keys

v1/opt/aqua/fleet/aqua-agent.service
* Made aqua agent a global fleet unit for submission on all workers
=> Move Aqua Agent to Fleet Global

v1/setup/leader/001-defaults.sh
* Using etcd for some configs instead of environment variables
=> Moving environment variable configs to etcd

v1/opt/aqua/setup/leader/001-images.sh
Any docker containers introduced through your commit must not accumulate logs in an unsustainable manner.  In other words, no unmanaged logs that aren't/can't be rotated.  
If your PR relies on the default docker log driver, `json`, then this simply means ensuring all `docker run` commands are decorated with either/both of `--log-opt max-size=XX` / `--log-opt max-file=YY` (see the docker documentation for valid XX/YY values)
If you did, have you ensured that all your `docker run` using the default logger have either `max-size` and/or …
=> Aqua gateway image 1.2.tp2

v1/fleet/control-booster.service, v1/fleet/worker-booster.service, v1/opt/aqua/fleet/aqua-agent.service, v1/opt/aqua/fleet/aqua-gateway.service, v1/opt/aqua/fleet/aqua-web.service
* Added a timeout to allow docker pull to complete before restarting
=> Adding Timeouts to Slow Docker Pulls

v1/fleet-local/control/flight-director@.service, v1/util/flight-director.sh
* Changed FD script to docker run directly
* Changed Restart to "always" for FD
=> Flight Director Restart Fix

v1/util/docker-cleanup.sh
- Fixes periodic docker artifact cleanup.  It decorates log lines so that there is some context
- Emit relevant lvm info as it relates to docker
Any docker containers introduced through your commit must not accumulate logs in an unsustainable manner.  In other words, no unmanaged logs that aren't/can't be rotated.  
If your PR relies on the default docker log driver, `json`, then this simply means ensuring all `docker run` commands are decorated with either/both of `--log-opt max-size=XX` / `--log-opt max-file=YY` (see the docker documentation for valid XX/YY values)
Did you introduce any command …
=> Removed dangerous cleanup as in mesos-systemd.

v1/setup/leader/001-defaults.sh
=> FD update for names that are too long (crashing mesos)

v1/opt/sumologic/fleet/journald-sumo-pipe.service, v1/opt/sumologic/fleet/sumologic-control.service, v1/opt/sumologic/fleet/sumologic-journald.service, v1/opt/sumologic/fleet/sumologic.service
* Added the AWS region to the Sumo log category
=> Adding region to Sumo log category

v1/fleet-local/proxy/proxy@.service, v1/util/ensure-proxy.sh
* Added a script that creates a dummy proxy config if none exists. This prevents proxy service from failing repeatedly.
=> Adding a dummy config for proxy service

v1/opt/aqua/fleet/aqua-web.service
=> remove timeout=infinity

v1/opt/aqua/util/aqua-agent-health.sh
=> wait 5 minutes for aqua agent before start mesos slave

init
=> Verify that Docker socket file ownership is set to root:docker

v1/fleet/chronos-cleanup.service, v1/fleet/chronos-cleanup.timer, v1/util/chronos-cleanup.sh
Add new chronos-cleanup.service and chronos-cleanup.timer
*No*
*No*
If so:
*No*
*Yes*
No, but if this PR is merged, we'll need to add in chronos authentication: https://github.com/adobe-platform/ethos-systemd/pull/46
=> Chronos cleanup

v1/setup/leader/001-defaults.sh, v1/util/flight-director.sh
=> Chronos, Logging and Booster for FD

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
* Added CHANGELOG
* Updated PULL_REQUEST_TEMPLATE.md
=> Adding PR Template Changes and Changelog

v1/opt/aqua/fleet/aqua-image.service, v1/opt/aqua/util/aqua-image.sh
_Please enter each change as a new bullet point_
If so:
Is an update to the base stack required(rare)? No
Is an A/B required? Yes
Are you dependent on new secrets, or infrastructure in any way? No
Did you update CHANGELOG.md? No
None
https://docs.aquasec.com/docs/image-manipulation
CC: @adobe-platform/ethos-systemd-reviewers
=> authorize images in aqua worker nodes
